[package]
name = "wcal"
license = "MIT"
version = "0.2.0"
authors = ["Haruka <harukawei99@gmail.com>"]
edition = "2018"
description = "A calculator include lexer and parser."
readme = "README.md"
repository = "https://github.com/weijunji/wcal"

[dependencies]
logos = "0.12.0"