name: Releases

on: 
  push:
    tags:
    - '*'

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc
        override: true
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --bins --target x86_64-pc-windows-msvc
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "target/x86_64-pc-windows-msvc/release/wcal.exe, target/x86_64-pc-windows-msvc/release/wcal.pdb"
        bodyFile: "body.md"
        token: ${{ secrets.GITHUB_TOKEN }}
